name: Greeting Action
description: A simple action to greet the user
inputs:
  user:
    description: 'Name of the person to greet'
    required: true
    default: 'Welcome GitHub User'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    user: ${{ inputs.user }}