name: python setup composite action
description: A composite action to set up Python environment
runs:
  using: "composite"
  steps:

    - name: Printing the Actor Name
      run: |
        echo "The actor name is: ${{ github.actor }}"
      shell: bash  

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install pandas
        pip install numpy
      shell: bash  
    
    - name: List the installed packages
      run: |
        pip list
      shell: bash