name: python setup composite action
description: A composite action to set up Python environment
inputs:
  packages:
    description: 'List of Python packages to install'
    required: false
    default: 'pandas'
runs:
  using: "composite"
  steps:

    - name: Printing the Actor Name
      run: |
        echo "The actor name is: ${{ github.actor }}"
      shell: bash  

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install ${{ inputs.packages }}
      shell: bash  
    
    - name: List the installed packages
      run: |
        pip list
      shell: bash