# Organization - Precedence is low but visibility is high
# Repository
# Workflow
# Job
# Step - Precedence is high but visibility is low



name: 03 - Variables
on:
  push:
env:
  MY_VAR3: "This is a Global variable."    
jobs:
    my-variables-job-01:
        name: variables demo - 01
        runs-on: ubuntu-latest
        env:
          MY_VAR1: "This is a Job variable."
        steps:
            - name: my step variables
              run: |
                echo "$MY_VAR_2"
              env:
                MY_VAR_2: "This is a Step variable."  

            - name: printing MY_VAR2 step variables
              run: |
                echo "$MY_VAR_2"
                
            - name: printing MY_VAR1 job variables
              run: |
                echo "$MY_VAR1"
            
            - name: printing MY_VAR3 wf variables
              run: |
                echo "$MY_VAR3"       
            
            - name: printing Repostitory variables
              run: |
                echo "My user is ${{ vars.MY_USER }}"                
                echo "My secret is ${{ secrets.MY_PASSWORD }}"  


    # my-variables-job-02:
    #     name: variables demo - 02
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: printing MY_VAR1 job variables
    #           run: |
    #             echo "$MY_VAR1"

    #         - name: printing MY_VAR3 wf variables
    #           run: |
    #             echo "$MY_VAR3"              
