# Workflow
# Job
# Step

# Repository
# Organization

name: 03 - Variables
on:
  push:
jobs:
    my-variables-job:
        name: variables demo
        runs-on: ubuntu-latest
        steps:
            - name: my step variables
              run: |
                echo "$MY_VAR"
              env:
                MY_VAR: "Hello, world! This is a variable."  