# Organization
# Repository
# Workflow
# Job
# Step - Precedence is high but visibility is low



name: 03 - Variables
on:
  push:
jobs:
    my-variables-job-01:
        name: variables demo
        runs-on: ubuntu-latest
        env:
          MY_VAR1: "This is a Job variable."
        steps:
            - name: my step variables
              run: |
                echo "$MY_VAR_2"
              env:
                MY_VAR_2: "This is a Step variable."  

            - name: printing MY_VAR2 step variables
              run: |
                echo "$MY_VAR_2"
                
            - name: printing MY_VAR1 job variables
              run: |
                echo "$MY_VAR1"
                
    my-variables-job-02:
        name: variables demo
        runs-on: ubuntu-latest
        steps:
            - name: printing MY_VAR1 job variables
              run: |
                echo "$MY_VAR1"