name: 06-design-with-needs
on:
    push:
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Build the project
              run: echo "Building the project..."    

    unit-test:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - name: Run unit tests
              run: echo "Running unit tests..."

    quality-check:
        name: Quality Check
        runs-on: ubuntu-latest
        steps:
            - name: Perform quality checks
              run: echo "Performing quality checks..."

    deploy:
        name: Deploy Application
        runs-on: ubuntu-latest
        steps:
            - name: Deploy the application
              run: echo "Deploying the application..."