name: 08-manual-workflow
on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a manual script
        run: |
          echo Hello, world!
          echo This is a manual workflow.