name: 09 - Matrix Workflow
on:
  push:
jobs:
    my-first-job:
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-22.04, ubuntu-18.04]
                image: [python:3.9, python:3.8, python:3.7]
        name: job-${{ matrix.os }}-${{ matrix.image }}
        runs-on: ${{ matrix.os }}
        steps:
            - name: Run a multi-line script
              run: |
                echo Hello, world!
                echo This is a multi-line script.

            - name: Run a single-line script
              run: echo Hello, world! single line
    