# failure, success, cancelled, skipped
name: 10 - Status Checks
on: [push]
jobs:
  status-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
            echo "Running Build..."
            exit 1

      - name: Generate Error Report
        if: failure()
        run: |
            echo "Running Generate Error Report..."

      - name: Unit Testing
        run: |
            echo "Running Unit Testing..."

      - name: Deployment
        run: |
            echo "Running Deployment"
    

