name: 12-caller-wf
on: [push]
jobs:
    workflow-caller:
        uses: ./.github/workflows/12-callee-wf.yml
    another-job:
        runs-on: ubuntu-latest
        steps:
            - name: Run a script in the caller workflow
              run: |
                echo "This is the caller workflow."
                echo "You can add any steps you want here."
                echo "For example, you can run tests, deploy code, or send notifications."
                echo "This workflow calls another workflow."    