name: 15-calling-composite-action
on: [push]
jobs:
  call-composite-action:
    runs-on: ubuntu-latest
    steps:
      - name: Call the composite action
        uses: ./.github/actions/python-setup

          
