name: 17-cache-wf
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: find cache dir
        run: |
           pip cache dir
          
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-pip
        with:
          path: |
            ~/.cache/pip
            /home/runner/.cache/pip
          #key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          key: mycache-07102025-key
          restore-keys: |
            mycache-07102025

      - name: Install dependencies
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn pytest            