name: My First Workflow
on: 
  push:
  
jobs:  
  my-first-workflow:
    name: learning thru my first workflow job
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - name: Echo VAR1
        run: echo ${{ env.VAR1 }}
        env: { VAR1: "Hello from my first workflow!" }